name: MoleGuLAR
channels:
  - rdkit
  - pytorch
  - dglteam
  - hcc
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - autodock=4.2.6=hfc679d8_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.7.5=h06a4308_1
  - cairo=1.16.0=hf32fb01_1
  - certifi=2021.5.30=py37h06a4308_0
  - cffi=1.14.6=py37h400218f_0
  - chardet=4.0.0=py37h06a4308_1003
  - cryptography=3.4.7=py37hd23ed53_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py37_0
  - dbus=1.13.18=hb2f20db_0
  - dgl=0.6.1=py37_0
  - dgllife=0.2.6=py37_0
  - expat=2.4.1=h2531618_2
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.69.0=h5202010_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py37h2531618_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libboost=1.73.0=h3ff78a5_11
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h2531618_0
  - matplotlib=3.3.4=py37h06a4308_0
  - matplotlib-base=3.3.4=py37h62a2d02_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.6.1=pyhd3eb1b0_0
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.3=py37hf144106_0
  - numpy-base=1.20.3=py37h74d4b33_0
  - olefile=0.46=py37_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1k=h27cfd23_0
  - pandas=1.2.5=py37h295c915_0
  - pcre=8.45=h295c915_0
  - pillow=8.3.1=py37h2c7a002_0
  - pip=21.1.3=py37h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - py-boost=1.73.0=py37ha9443f7_11
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37_1
  - python=3.7.10=h12debd9_4
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.9.0=py3.7_cuda10.2_cudnn7.6.5_0
  - pytz=2021.1=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - rdkit=2020.09.1.0=py37hd50e099_1
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - scikit-learn=0.24.2=py37ha9443f7_0
  - scipy=1.6.2=py37had2a1c9_1
  - setuptools=52.0.0=py37h06a4308_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - threadpoolctl=2.2.0=pyhb85f177_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py37h27cfd23_0
  - tqdm=4.61.2=pyhd3eb1b0_1
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==21.2.0
    - backcall==0.2.0
    - bleach==3.3.1
    - click==8.0.1
    - configparser==5.0.2
    - debugpy==1.3.0
    - decorator==5.0.9
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - entrypoints==0.3
    - gitdb==4.0.7
    - gitpython==3.1.18
    - importlib-metadata==3.10.1
    - ipykernel==6.0.3
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.12
    - jupyter-console==6.4.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.0
    - packaging==21.0
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickle5==0.0.11
    - pickleshare==0.7.5
    - prometheus-client==0.11.0
    - promise==2.3
    - prompt-toolkit==3.0.19
    - protobuf==3.17.3
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pygments==2.9.0
    - pyrsistent==0.18.0
    - pyyaml==5.4.1
    - pyzmq==22.1.0
    - qtconsole==5.1.1
    - qtpy==1.9.0
    - seaborn==0.11.1
    - send2trash==1.7.1
    - sentry-sdk==1.3.0
    - shortuuid==1.0.1
    - smmap==4.0.0
    - subprocess32==3.5.4
    - terminado==0.10.1
    - testpath==0.5.0
    - traitlets==5.0.5
    - wandb==0.11.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.5.0
